/*******************************************************************************
 *  Copyright (c) 2015 IBM Corporation.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_layout_UnsafeHelper */

#ifndef _Included_com_ibm_layout_UnsafeHelper
#define _Included_com_ibm_layout_UnsafeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_layout_UnsafeHelper
 * Method:    bufferFromAddressImpl
 * Signature: (JJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_layout_UnsafeHelper_bufferFromAddressImpl
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_layout_UnsafeHelper
 * Method:    getDBBAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_layout_UnsafeHelper_getDBBAddress
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_ibm_layout_UnsafeHelper
 * Method:    getDBBLength
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_layout_UnsafeHelper_getDBBLength
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
