/*******************************************************************************
 *  Copyright (c) 2016 IBM Corporation.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package com.user.types;

import com.ibm.layout.BooleanPointer ;
import com.ibm.layout.Layout;
import com.ibm.layout.LayoutDesc;

/* Generated by LD2J */
@LayoutDesc({"value:jboolean:1"})
public interface Boolean extends Layout {

	interface EffectiveAddress {

		public BooleanPointer value();

	}

	public Boolean.EffectiveAddress EA();

	public long sizeof();

	public boolean value();

	public void value(boolean val);

	@Override
	public String toString();

}
