/*******************************************************************************
 *  Copyright (c) 2016 IBM Corporation.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package com.user.types;

import com.ibm.layout.CharPointer ;
import com.ibm.layout.Layout;
import com.ibm.layout.LayoutDesc;

/* Generated by LD2J */
@LayoutDesc({"value:jchar:2"})
public interface Char extends Layout {

	interface EffectiveAddress {

		public CharPointer value();

	}

	public Char.EffectiveAddress EA();

	public long sizeof();

	public char value();

	public void value(char val);

	@Override
	public String toString();

}
