/*******************************************************************************
 *  Copyright (c) 2016 IBM Corporation.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package com.user.types;

import com.ibm.layout.IntPointer ;
import com.ibm.layout.IntArray2D;
import com.ibm.layout.Layout;
import com.ibm.layout.LayoutDesc;

/* Generated by LD2J */
@LayoutDesc({"m:jint[2][2]:16","n:jint[2][2]:16","p:jint[2][2]:16"})
public interface IntM3 extends Layout {

	interface EffectiveAddress {

		public IntPointer m();

		public IntPointer n();

		public IntPointer p();

	}

	public IntM3.EffectiveAddress EA();

	public long sizeof();

	public IntArray2D m();

	public IntArray2D n();

	public IntArray2D p();

	@Override
	public String toString();

}
