/*******************************************************************************
 *  Copyright (c) 2016 IBM Corporation.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package com.user.types;

import com.ibm.layout.Pointer;
import com.ibm.layout.Layout;
import com.ibm.layout.LayoutDesc;

/* Generated by LD2J */
@LayoutDesc({"st:Point:8","en:Point:8"})
public interface Line extends Layout {

	interface EffectiveAddress {

		public Pointer<Point> st();

		public Pointer<Point> en();

	}

	public Line.EffectiveAddress EA();

	public long sizeof();

	public Point st();

	public Point en();

	@Override
	public String toString();

}
