/*******************************************************************************
 *  Copyright (c) 2016 IBM Corporation.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package com.user.types;

import com.ibm.layout.Pointer;
import com.ibm.layout.Array2D;
import com.ibm.layout.Layout;
import com.ibm.layout.LayoutDesc;

/* Generated by LD2J */
@LayoutDesc({"m:Int[2][2]:16","n:Int[2][2]:16","p:Int[2][2]:16"})
public interface M3 extends Layout {

	interface EffectiveAddress {

		public Pointer<Int> m();

		public Pointer<Int> n();

		public Pointer<Int> p();

	}

	public M3.EffectiveAddress EA();

	public long sizeof();

	public Array2D<Int> m();

	public Array2D<Int> n();

	public Array2D<Int> p();

	@Override
	public String toString();

}
