/*******************************************************************************
 *  Copyright (c) 2016 IBM Corporation.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html 
 *******************************************************************************/
package com.user.types;

import com.ibm.layout.VLArray;
import com.user.types.ArrayElement;
import com.ibm.layout.Layout;
import com.ibm.layout.Location;
import com.ibm.layout.LayoutDesc;

/* Generated by LD2J */
@LayoutDesc({"lengthOfArray:jchar:2","elements:ArrayElement[lengthOfArray]:0"})
public interface VariableLengthArrayWithCharRepeatCount extends Layout {

	public long sizeof();

	public abstract char lengthOfArray();

	public abstract VLArray<ArrayElement> elements();

	public void bindLocation(Location loc, char repeatCountInitializer);

	@Override
	public String toString();

}
