/*******************************************************************************
 *  Copyright (c) 2016 IBM Corporation.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package com.user.types;

import com.ibm.layout.BytePointer ;
import com.ibm.layout.Pointer;
import com.ibm.layout.Location;
import com.ibm.layout.VLArray;
import com.ibm.layout.Layout;
import com.ibm.layout.LayoutDesc;

/* Generated by LD2J */
@LayoutDesc({"lengthOfArray:jbyte:1","elements:ArrayElement[lengthOfArray]:0"})
public interface VariableLengthArrayWithByteRepeatCount extends Layout {

	interface EffectiveAddress {

		public BytePointer lengthOfArray();

		public Pointer<ArrayElement> elements();

	}

	public VariableLengthArrayWithByteRepeatCount.EffectiveAddress EA();

	public long sizeof();

	public byte lengthOfArray();

	public VLArray<ArrayElement> elements();

	public void bindLocation(Location loc, byte repeatCountInitializer);

	@Override
	public String toString();

}
