/*******************************************************************************
 *  Copyright (c) 2016 IBM Corporation.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package com.user.types;

import com.ibm.layout.BytePointer ;
import com.ibm.layout.Pointer;
import com.ibm.layout.VLArray;
import com.ibm.layout.Layout;
import com.ibm.layout.LayoutDesc;

/* Generated by LD2J */
@LayoutDesc({"a:jbyte:1","b:Byte[a]:0","c:jbyte:1","d:Byte[c]:0","e:jbyte:1","f:Byte[e]:0"})
public interface VLS1 extends Layout {

	interface EffectiveAddress {

		public BytePointer a();

		public Pointer<Byte> b();

		public BytePointer c();

		public Pointer<Byte> d();

		public BytePointer e();

		public Pointer<Byte> f();

	}

	public VLS1.EffectiveAddress EA();

	public long sizeof();

	public byte a();

	public VLArray<Byte> b();

	public byte c();

	public VLArray<Byte> d();

	public byte e();

	public VLArray<Byte> f();

	public void a(byte val);

	public void c(byte val);

	@Override
	public String toString();

}
