/*******************************************************************************
 *  Copyright (c) 2016 IBM Corporation.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package com.user.types;

import com.ibm.layout.LongPointer ;
import com.ibm.layout.Pointer;
import com.ibm.layout.VLArray;
import com.ibm.layout.Layout;
import com.ibm.layout.LayoutDesc;

/* Generated by LD2J */
@LayoutDesc({"a:jlong:8","b:Long[a]:0","c:jlong:8","d:Long[c]:0","e:jlong:8","f:Long[e]:0"})
public interface VLSLong1 extends Layout {

	interface EffectiveAddress {

		public LongPointer a();

		public Pointer<Long> b();

		public LongPointer c();

		public Pointer<Long> d();

		public LongPointer e();

		public Pointer<Long> f();

	}

	public VLSLong1.EffectiveAddress EA();

	public long sizeof();

	public long a();

	public VLArray<Long> b();

	public long c();

	public VLArray<Long> d();

	public long e();

	public VLArray<Long> f();

	public void a(long val);

	public void c(long val);

	@Override
	public String toString();

}
