/*******************************************************************************
 *  Copyright (c) 2016 IBM Corporation.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package com.user.examples.javaclassfile;

import com.ibm.layout.ShortPointer ;
import com.ibm.layout.IntPointer ;
import com.ibm.layout.Pointer;
import com.ibm.layout.Location;
import com.ibm.layout.VLArray;
import com.ibm.layout.Layout;
import com.ibm.layout.LayoutDesc;

/* Generated by LD2J */
@LayoutDesc({">attrNameIndex:jshort:2",">attrLength:jint:4",">info:Byte[attrLength]:0"})
public interface Attributes extends Layout {

	interface EffectiveAddress {

		public ShortPointer attrNameIndex();

		public IntPointer attrLength();

		public Pointer<Byte> info();

	}

	public Attributes.EffectiveAddress EA();

	public long sizeof();

	public short attrNameIndex();

	public int attrLength();

	public VLArray<Byte> info();

	public void bindLocation(Location loc, int repeatCountInitializer);

	public void attrNameIndex(short val);

	@Override
	public String toString();

}
