/*******************************************************************************
 *  Copyright (c) 2016 IBM Corporation.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package com.user.examples.javaclassfile;

import com.ibm.layout.BytePointer ;
import com.user.examples.javaclassfile.CPEntryPayload;
import com.ibm.layout.Pointer;
import com.ibm.layout.Layout;
import com.ibm.layout.LayoutDesc;

/* Generated by LD2J */
@LayoutDesc({">tag:jbyte:1",">info:Byte[tag]:0"})
public interface CPEntry extends Layout {

	interface EffectiveAddress {

		public BytePointer tag();

		public Pointer<Byte> info();

	}

	public CPEntry.EffectiveAddress EA();

	public long sizeof();

	public byte tag();

	public CPEntryPayload<Byte> info();

	@Override
	public String toString();

}
