/*******************************************************************************
 *  Copyright (c) 2016 IBM Corporation.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package com.user.examples.javaclassfile;

import com.ibm.layout.LongPointer ;
import com.ibm.layout.Layout;
import com.ibm.layout.LayoutDesc;

/* Generated by LD2J */
@LayoutDesc({">val:jlong:8"})
public interface Long extends Layout {

	interface EffectiveAddress {

		public LongPointer val();

	}

	public Long.EffectiveAddress EA();

	public long sizeof();

	public long val();

	public void val(long val);

	@Override
	public String toString();

}
