/*******************************************************************************
 *  Copyright (c) 2016 IBM Corporation.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package com.user.examples.javaclassfile;

import com.ibm.layout.ShortPointer ;
import com.ibm.layout.Pointer;
import com.ibm.layout.Location;
import com.ibm.layout.VLArray;
import com.ibm.layout.Layout;
import com.ibm.layout.LayoutDesc;

/* Generated by LD2J */
@LayoutDesc({">accessFlags:jshort:2",">nameIndex:jshort:2",">descriptorIndex:jshort:2",">attributesCount:jshort:2",">attributeInfo:Attributes[attributesCount]:0"})
public interface Methods extends Layout {

	interface EffectiveAddress {

		public ShortPointer accessFlags();

		public ShortPointer nameIndex();

		public ShortPointer descriptorIndex();

		public ShortPointer attributesCount();

		public Pointer<Attributes> attributeInfo();

	}

	public Methods.EffectiveAddress EA();

	public long sizeof();

	public short accessFlags();

	public short nameIndex();

	public short descriptorIndex();

	public short attributesCount();

	public VLArray<Attributes> attributeInfo();

	public void bindLocation(Location loc, short repeatCountInitializer);

	public void accessFlags(short val);

	public void nameIndex(short val);

	public void descriptorIndex(short val);

	@Override
	public String toString();

}
