/*******************************************************************************
 *  Copyright (c) 2016 IBM Corporation.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package com.user.examples.vlawithoperation;

import com.ibm.layout.BytePointer ;
import com.user.examples.vlawithoperation.SubOne;
import com.user.examples.vlawithoperation.AddOne;
import com.ibm.layout.Pointer;
import com.ibm.layout.Layout;
import com.ibm.layout.LayoutDesc;

/* Generated by LD2J */
@LayoutDesc({"a:jbyte:1","b:Byte[a]:0","c:jbyte:1","d:Byte[c]:0"})
public interface VlaWithOperation extends Layout {

	interface EffectiveAddress {

		public BytePointer a();

		public Pointer<Byte> b();

		public BytePointer c();

		public Pointer<Byte> d();

	}

	public VlaWithOperation.EffectiveAddress EA();

	public long sizeof();

	public byte a();

	public SubOne<Byte> b();

	public byte c();

	public AddOne<Byte> d();

	public void a(byte val);

	@Override
	public String toString();

}
